### ISSUE TITLE
Deploy on F-Droid

### ISSUE THREAD

**Issue by vishal2376** [vishal2376/snaptick#6]
### Note :  Metadata is already added (in fastlane structure)

**Comment by yogeshpaliyal** [comment]
@vishal2376 
I can help here, My app is already on F-droid.

**Comment by vishal2376** [comment]
@yogeshpaliyal It would be great, if you help in Publishing app on Fdroid

**Comment by yogeshpaliyal** [comment]
@licaon-kter can you please help

**Comment by licaon-kter** [comment]
Will take a look asap

**Comment by licaon-kter** [comment]
this recipe **metadata/com.vishal2376.snaptick.yml**
```
Categories:
  - Time
License: GPL-3.0-only
SourceCode: https://github.com/vishal2376/snaptick
IssueTracker: https://github.com/vishal2376/snaptick/issues

AutoName: Snaptick

RepoType: git
Repo: https://github.com/vishal2376/snaptick.git
Binaries: https://github.com/vishal2376/snaptick/releases/download/v%v/snaptick.v%v.apk

Builds:
  - versionName: '3.0'
    versionCode: 8
    commit: 9f52c401880623b0d793c5e4eb0878b54e2c7002
    subdir: app
    gradle:
      - yes

AllowedAPKSigningKeys: 637c4d767b7e78337a9f3f0a3d1e17766366d050a75f770da446289e08caf649

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: '3.0'
CurrentVersionCode: 8
```
builds but not yet reproducible (ref: https://f-droid.org/docs/Inclusion_How-To/#reproducible-builds )

```
==== detail begin ====
verification of APK with copied signature failed
Comparing reference APK to APK with copied signature...
Unexpected diff output:
Binary files /tmp/tmpy3m3tbpn/unsigned_binaries_com.vishal2376.snaptick_8.binary/content/assets/dexopt/baseline.prof and /tmp/tmpy3m3tbpn/_tmp_tmpy3m3tbpn_sigcp_com.vishal2376.snaptick_8/content/assets/dexopt/baseline.prof differ
Binary files /tmp/tmpy3m3tbpn/unsigned_binaries_com.vishal2376.snaptick_8.binary/content/assets/dexopt/baseline.profm and /tmp/tmpy3m3tbpn/_tmp_tmpy3m3tbpn_sigcp_com.vishal2376.snaptick_8/content/assets/dexopt/baseline.profm differ
Binary files /tmp/tmpy3m3tbpn/unsigned_binaries_com.vishal2376.snaptick_8.binary/content/classes3.dex and /tmp/tmpy3m3tbpn/_tmp_tmpy3m3tbpn_sigcp_com.vishal2376.snaptick_8/content/classes3.dex differ
==== detail end ====
```
yet, it might look like it's a known issue like: https://gitlab.com/fdroid/fdroiddata/-/issues/3138

so, can you update those kotlin libs to 1.5.11 & 1.9.23 ( https://developer.android.com/jetpack/androidx/releases/compose-kotlin#pre-release_kotlin_compatibility ) and we can compare to that new APK?
